server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springSecurity?serverTimezone=Asia/Seoul
    username: test
    password: yeong1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 374299965772-1cbitap95r8n22pj959704p6fh8are20.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile


logging:
  level:
    org.hibernate.SQL: debug

