spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 354831073067328
            client-secret: 451e7067725f22c684262c91ed9cf897
          google:
            client-id: 318908294721-ued1s1t63jkuo1hv6aj0uj3sv9h4mcr7.apps.googleusercontent.com
            client-secret: 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